version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - app
    volumes:
      - .:/app

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2db_6g5T5YBscm
      MYSQL_USER: yii2db_admin
      MYSQL_PASSWORD: yii2db_admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
